<?php

namespace Database\Seeders;

use App\Models\ChoiceType;
use App\Models\MasterChoice;
use Illuminate\Database\Seeder;

class ChoiceTypeSeeder extends Seeder
{
    public function run(): void
    {
        // Source: Django apps/base/management/commands/populate_master_choices.py
        $map = [
            'gender' => [
                ['Male', 'ذكر'],
                ['Female', 'أنثى'],
            ],
            'learning_type' => [
                ['Course', 'دورة'],
                ['Class', 'درس'],
                ['Consultation', 'استشارة'],
                ['Internship', 'تدريب عملي'],
                ['internship', 'تدريب'],
                ['course', 'دورة'],
            ],
            'learn_serve_format' => [
                ['ONLINE', 'عن بعد'],
                ['IN PERSON', 'حضوري'],
                ['Online', 'عن بعد'],
                ['Onsite', 'حضوري'],
            ],
            'learn_serve_certificate_type' => [
                ['Forsa Certificate', 'شهادة فرصة'],
                ["Organizer's Certificate", 'شهادة المنظم'],
                ['forsa certificate', 'شهادة فرصة'],
                ["organizer's certificate", 'شهادة الجهة'],
            ],
            'org_type' => [
                ['Volunteer Team', 'فريق تطوعي'],
                ['Private', 'خاص'],
                ['Public', 'عام'],
                ['Company', 'شركة'],
                ['NGO', 'منظمة غير ربحية'],
                ['Government', 'حكومي'],
            ],
            'sponsor_type' => [
                ['Financial sponsor', 'رعاية مالية'],
                ['Supporting Partner', 'شريك داعم'],
                ['Media sponsor', 'رعاية إعلامية'],
                ['Gold', 'ذهبي'],
                ['Silver', 'فضي'],
            ],
            'type_of_support' => [
                ['Logistical Support', 'الدعم اللوجستي'],
                ['Gold', 'ذهبي'],
                ['Silver', 'فضي'],
                ['Bronze', 'برونزي'],
                ['Incentive Gifts', 'هدية تحفيزية'],
                ['Equipment and Tools', 'معدات وأدوات'],
                ['Services', 'خدمات'],
                ['Media', 'إعلامي'],
                ['Other', 'آخر'],
                ['Financial', 'مالي'],
                ['In-kind', 'عيني'],
            ],
            'sector' => [
                ['Government Sector', 'الحكومي'],
                ['Banks', 'البنوك'],
                ['Insurance', 'التأمين'],
                ['Investment Companies', 'شركات الاستثمار'],
                ['Financing Companies', 'شركات التمويل'],
                ['Financial Technology (FinTech)', 'التقنية المالية (FinTech)'],
                ['Trade / Commerce', 'التجارة'],
                ['Healthcare', 'الصحه'],
                ['Education', 'التعليم'],
                ['Agriculture', 'الزراعه'],
                ['Construction & Real Estate', 'قطاع البناء والعقارات'],
                ['Industry / Manufacturing', 'قطاع الصناعه'],
                ['Furniture', 'الأثاث'],
                ['Shopping Mall / Commercial Complex', 'مجمع تجاري'],
                ['Food & Nutrition', 'التغذيه'],
                ['Energy', 'الطاقه'],
                ['Services', 'الخدمات'],
                ['Legal / Law', 'القانون'],
                ['Technology', 'التكنولوجيا'],
                ['Media & Communication', 'الاعلام'],
                ['Logistics', 'اللوجستي'],
                ['Cooperative Society', 'جمعية تعاونية'],
                ['Volunteer Team', 'فريق تطوعي'],
                ['Association', 'جمعية'],
                ['Non-Profit', 'غير ربحي'],
                ['Health', 'الصحة'],
            ],
            'opportunity_gender' => [
                ['Male', 'ذكر'],
                ['Female', 'أنثى'],
                ['Both', 'كلاهما'],
                ['All', 'الكل'],
            ],
            'event_type' => [
                ['Expo & Carnival', 'معارض ومهرجانات'],
                ['Camps', 'المعسكرات'],
                ['Hub', 'مساحة'],
                ['Sport Activity', 'أنشطة رياضية'],
                ['Entertainment', 'ترفيه'],
                ['Workshop', 'ورش عمل'],
                ['Competitions', 'مسابقات'],
                ['Program', 'برنامج'],
                ['Scholarship', 'منحة'],
                ['Training', 'تدريب'],
                ['Show', 'عرض'],
                ['Conference', 'مؤتمر'],
                ['Meetup', 'لقاء'],
            ],
            'payment_status' => [
                ['Pending', 'قيد الانتظار'],
                ['Paid', 'مدفوع'],
                ['Refunded', 'مسترد'],
                ['Failed', 'فشل الدفع'],
            ],
            'volunteer_opportunity_interest' => [
                ['Community Service', 'خدمة مجتمعية'],
                ['Arts & Creativity', 'الفنون والابداع'],
                ['Local Emergencies', 'طوارئ محليه'],
                ['Event Management & Organization', 'تنظيم واداره الفعاليات'],
                ['Professional', 'مهني'],
                ['Ramadan Activities', 'رمضانيات'],
                ['Charity Work', 'أعمال خيرية'],
                ['Kids', 'أطفال'],
                ['Health', 'الصحة'],
                ['Environment', 'البيئة'],
                ['Relief', 'إغاثي'],
                ['Retirees', 'متقاعدين'],
                ['Sports', 'رياضي'],
                ['Animal Care', 'حيوانات'],
                ['Safety and Security', 'الأمن والسلامة'],
                ['General', 'عام'],
                ['Technology', 'تقني'],
                ['Religious', 'ديني'],
                ['Community', 'مجتمع'],
                ['Education', 'تعليم'],
            ],
            'learnserve_opportunity_interest' => [
                ['Kids', 'أطفال'],
                ['Marketing & Content Creation', 'التسويق وصناعة المحتوى'],
                ['Business & Finance', 'الأعمال والمال'],
                ['Other', 'اخري'],
                ['Nutrition & Culinary Arts', 'التغذية وفنون الطهي'],
                ['Religious', 'دينية'],
                ['Tutoring', 'دروس تقوية'],
                ['Arts & Crafts Skills', 'المهارات الفنية والحرفية'],
                ['Design', 'التصميم'],
                ['Languages', 'اللغات'],
                ['Technology & Programming', 'التقنية والبرمجة'],
                ['AI & Digital Transformation', 'الذكاء الاصطناعي والتحول الرقمي'],
                ['Self Development', 'التنمية الذاتية'],
                ['Law & Regulations', 'القانون والأنظمة'],
                ['Environment & Sustainability', 'البيئة والاستدامة'],
                ['Sports', 'الرياضة'],
                ['Family & Parenting', 'الأسرة والتربية'],
                ['Health', 'الصحة'],
                ['Practical Training', 'التدريب العملي'],
                ['Theater & Acting', 'المسرح والتمثيل'],
                ['Writing', 'الكتابة'],
                ['Internship', 'تدريب'],
                ['Course', 'دورة'],
            ],
            'event_interest' => [
                ['Arts & Culture', 'فني وثقافي'],
                ['Kids', 'أطفال'],
                ['Food / Nutrition', 'طعام/تغذية'],
                ['Furniture', 'اثاث'],
                ['Books', 'كتب'],
                ['Trips / Travel', 'رحلات'],
                ['General', 'عام'],
                ['Sports', 'رياضي'],
                ['Cultural', 'ثقافي'],
                ['Religious', 'ديني'],
                ['Cars', 'سيارات'],
                ['Perfumes', 'عطور'],
                ['Health', 'صحي'],
                ['Economic', 'اقتصادي'],
                ['Employment', 'وظيفي'],
                ['Anime', 'أنمي'],
                ['Handicrafts', 'حرفي'],
                ['Environmental', 'بيئي'],
                ['Technological', 'تقني'],
                ['Entertainment', 'ترفيهي'],
                ['Real Estate', 'عقاري'],
                ['Sea & Desert', 'بحر/ بر'],
                ['Academic', 'أكاديمي'],
                ['Scientific', 'علمي'],
                ['Networking', 'تواصل'],
                ['Workshop', 'ورشة'],
            ],
            'user_interest' => [
                ['Kids', 'أطفال'],
                ['Arts and Culture', 'الثقافة والفنون'],
                ['Sports & Health', 'الرياضة والصحة'],
                ['Education & Learning', 'التعليم والمعرفة'],
                ['Business & Economy', 'الأعمال والاقتصاد'],
                ['Design', 'التصميم'],
                ['Environment & Sustainability', 'البيئة والاستدامة'],
                ['Technology', 'التقنية'],
                ['Animals', 'الحيوانات'],
                ['Volunteer', 'تطوع'],
                ['Sports', 'رياضة'],
                ['Arts', 'فنون'],
                ['Environment', 'بيئة'],
            ],
            'event_attendance_type' => [
                ['Subscription', 'الاشتراك'],
                ['Fixed Date Entry', 'إدخال تاريخ ثابت'],
                ['Flexible One-Day Entry', 'دخول مرن ليوم واحد'],
                ['Open', 'مفتوح'],
                ['Ticketed', 'بتذاكر'],
            ],
            'filter-type' => [
                ['Volunteer', 'تطوع'],
                ['Course', 'دورة'],
                ['Class', 'درس'],
                ['Internship', 'تدريب عملي'],
                ['Consultation', 'استشارة'],
            ],
            'event_participation_type' => [
                ['Paid Event', 'فعالية مدفوعة'],
                ['Free Event', 'فعالية مجانية'],
                ['Free Event (Registration Required)', 'فعالية مجانية(التسجيل مطلوب)'],
                ['Individual', 'فردي'],
                ['Team', 'فريق'],
            ],
            'emergency_contact_relationship' => [
                ['Mother', 'الأم'],
                ['Grandfather', 'الجد'],
                ['Father', 'الأب'],
                ['Grandmother', 'الجدة'],
                ['Brother', 'الأخ'],
                ['Sister', 'الأخت'],
                ['Uncle', 'العم'],
                ['Aunt', 'العمة'],
                ['Maternal Uncle', 'الخال'],
                ['Maternal Aunt', 'الخالة'],
                ['Parent', 'والد/والدة'],
                ['Guardian', 'وصي'],
                ['Sibling', 'أخ/أخت'],
            ],
        ];

        foreach ($map as $typeName => $values) {
            $type = ChoiceType::query()->firstOrCreate(['name' => $typeName]);
            foreach ($values as [$en, $ar]) {
                MasterChoice::query()->firstOrCreate(
                    [
                        'choice_type_id' => $type->id,
                        'value_en' => $en,
                    ],
                    [
                        'value_ar' => $ar,
                    ]
                );
            }
        }
    }
}
